variables:
  AWS_DEFAULT_REGION: eu-central-1

stages:
  - test
  - deploy

test:
  stage: test
  before_script:
    - aws ecr get-login --no-include-email | sh
    - ./setup/start-docker-compose
    - ./setup/setup-kong.sh ./keys
  script:
    - ./setup/run-tests
  after_script:
    - ./setup/stop-docker-compose

php publish:
  stage: deploy
  before_script:
    - aws ecr get-login --no-include-email | sh
  only:
    - nowhere
  except:
    - schedules
  script:
    - make snapshot
