#!/bin/bash

if [[ $1 == local ]]
then
    docker-compose --project-name coin-sdk-php-local up -d --build
else
	# remove port exposure to avoid conflicts
	sed -e 's/"[0-9][0-9]*:\([0-9][0-9]*\)"/"\1"/g' docker-compose.yaml > /tmp/docker-compose.yaml
	docker-compose --project-name coin-sdk-php-${CI_JOB_ID} --file /tmp/docker-compose.yaml --project-directory ${PWD} up -d --build \
		docker0 \
		kong-database \
		kong-migration \
		kong \
		api-stub
fi
