#!/bin/bash

if [[ $1 == local ]]
then
    docker-compose --project-name coin-sdk-php-local down
else
	docker-compose --project-name coin-sdk-php-${CI_JOB_ID} --file /tmp/docker-compose.yaml --project-directory ${PWD} down
fi
